main: me.kagglu.mazeplugin.Main
name: MazePlugin
version: 1.0
author: Kagglu
api-version: 1.13
commands:
  maze:
    description: Generates maze of given size
    usage: /maze (size) (block)
    permission: bukkit.command.reload